development:
  adapter: postgresql
  encoding: unicode
  database: AFAR_backend_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: AFAR_backend_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: AFAR_backend_production
  pool: 5
